### ISSUE TITLE
Missing cloudpickle library

### ISSUE THREAD

**Issue by paraita** [ow2-proactive/proactive-python-client#14]
From a fresh environment:

```bash
pip install proactive --upgrade
```

Works but then importing the module fails because of a missing dependency:

```python
$ python
Python 3.6.5 (default, Apr 14 2018, 13:17:30)
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import proactive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paraita/Bureau/SP/test_jupyroactive/ENV/lib/python3.6/site-packages/proactive/__init__.py", line 1, in <module>                                                                                     
    from .ProactiveGateway import *
  File "/home/paraita/Bureau/SP/test_jupyroactive/ENV/lib/python3.6/site-packages/proactive/ProactiveGateway.py", line 8, in <module>                                                                             
    from .ProactiveBuilder import *
  File "/home/paraita/Bureau/SP/test_jupyroactive/ENV/lib/python3.6/site-packages/proactive/ProactiveBuilder.py", line 1, in <module>                                                                             
    from .model.ProactiveTask import *
  File "/home/paraita/Bureau/SP/test_jupyroactive/ENV/lib/python3.6/site-packages/proactive/model/__init__.py", line 4, in <module>                                                                               
    from .ProactiveTask import *
  File "/home/paraita/Bureau/SP/test_jupyroactive/ENV/lib/python3.6/site-packages/proactive/model/ProactiveTask.py", line 2, in <module>                                                                          
    import cloudpickle
ModuleNotFoundError: No module named 'cloudpickle'
>>>

```

**Comment by paraita** [comment]
Fixed by #15
